import OpenAI from 'openai'

// Initialize OpenAI client
const openai = new OpenAI({
  apiKey: import.meta.env.VITE_OPENAI_API_KEY || 'demo-key',
  baseURL: "https://openrouter.ai/api/v1",
  dangerouslyAllowBrowser: true,
})

export async function generateRightsCard({ scenario, session, language, cardData }) {
  try {
    const scenarioTitle = scenario?.title[language] || scenario?.title.en || 'Legal Situation'
    const location = session?.location ? `Location: ${session.location.latitude.toFixed(4)}, ${session.location.longitude.toFixed(4)}` : ''
    const timestamp = new Date().toLocaleString()
    
    const prompt = `Create a concise, shareable legal rights summary card for the following scenario:

Scenario: ${scenarioTitle}
Language: ${language === 'es' ? 'Spanish' : 'English'}
Context: ${cardData?.type === 'emergency' ? 'Emergency recording session' : 'General rights information'}
${location}
Timestamp: ${timestamp}

Please generate a well-formatted text card that includes:
1. Title with scenario name
2. 4-5 key rights specific to this situation
3. 3-4 important phrases to use
4. 2-3 critical do's and don'ts
5. Footer with app name

Keep it under 300 words, mobile-friendly, and easily shareable. Use emojis for better readability.
${language === 'es' ? 'Respond entirely in Spanish.' : 'Respond in English.'}`

    const response = await openai.chat.completions.create({
      model: 'google/gemini-2.0-flash-001',
      messages: [
        {
          role: 'system',
          content: 'You are a legal rights assistant that creates clear, accurate, and concise rights summaries. Focus on constitutional rights and widely applicable legal principles.'
        },
        {
          role: 'user',
          content: prompt
        }
      ],
      max_tokens: 500,
      temperature: 0.3
    })

    const generatedContent = response.choices[0]?.message?.content || ''
    
    return {
      title: `${scenarioTitle} - ${language === 'es' ? 'Resumen de Derechos' : 'Rights Summary'}`,
      content: generatedContent,
      shareUrl: `${window.location.origin}/shared/${Date.now()}`,
      timestamp: Date.now(),
      language,
      scenario: scenario?.scenarioId
    }
    
  } catch (error) {
    console.error('Failed to generate AI card:', error)
    
    // Return fallback content
    return createFallbackCard(scenario, language)
  }
}

function createFallbackCard(scenario, language) {
  const isSpanish = language === 'es'
  const scenarioTitle = scenario?.title[language] || scenario?.title.en || (isSpanish ? 'Situación Legal' : 'Legal Situation')
  
  const content = isSpanish ? `
📋 Resumen de Derechos Legales

Escenario: ${scenarioTitle}
Generado: ${new Date().toLocaleDateString()}

🛡️ Derechos Clave:
• Derecho a permanecer en silencio
• Derecho a rechazar registros
• Derecho a preguntar "¿Soy libre de irme?"
• Derecho a un abogado

💬 Qué Decir:
• "Ejercito mi derecho a permanecer en silencio"
• "No consiento registros"
• "¿Soy libre de irme?"
• "Quiero hablar con un abogado"

⚠️ Importante:
• Mantén la calma y el respeto
• Mantén las manos visibles
• No discutas ni resistas
• Recuerda detalles para después

Generado por Zara Rights - Tu guía legal instantánea
  ` : `
📋 Your Legal Rights Summary

Scenario: ${scenarioTitle}
Generated: ${new Date().toLocaleDateString()}

🛡️ Key Rights:
• Right to remain silent
• Right to refuse searches
• Right to ask "Am I free to leave?"
• Right to an attorney

💬 What to Say:
• "I am exercising my right to remain silent"
• "I do not consent to searches"
• "Am I free to leave?"
• "I want to speak to a lawyer"

⚠️ Important:
• Stay calm and respectful
• Keep hands visible
• Don't argue or resist
• Remember details for later

Generated by Zara Rights - Your instant legal guide
  `

  return {
    title: `${scenarioTitle} - ${isSpanish ? 'Resumen de Derechos' : 'Rights Summary'}`,
    content: content.trim(),
    shareUrl: `${window.location.origin}/shared/${Date.now()}`,
    timestamp: Date.now(),
    language,
    scenario: scenario?.scenarioId
  }
}