import React, { useState, useEffect } from 'react'
import { ArrowLeft, Share2, Download, Copy, Check } from 'lucide-react'
import { CallToActionButton } from './CallToActionButton'
import { generateRightsCard } from '../services/cardGenerator'

export function ShareableCard({ scenario, session, cardData, language, onBack }) {
  const [generatedCard, setGeneratedCard] = useState(null)
  const [isGenerating, setIsGenerating] = useState(false)
  const [copied, setCopied] = useState(false)

  useEffect(() => {
    if (cardData) {
      generateCard()
    }
  }, [cardData, scenario, session])

  const generateCard = async () => {
    setIsGenerating(true)
    try {
      const card = await generateRightsCard({
        scenario,
        session,
        language,
        cardData
      })
      setGeneratedCard(card)
    } catch (error) {
      console.error('Failed to generate card:', error)
      // Fallback to static card
      setGeneratedCard(createFallbackCard())
    } finally {
      setIsGenerating(false)
    }
  }

  const createFallbackCard = () => {
    const scenarioTitle = scenario?.title[language] || scenario?.title.en || 'Legal Rights'
    
    return {
      title: `${scenarioTitle} - Rights Summary`,
      content: `
📋 Your Legal Rights Summary

Scenario: ${scenarioTitle}
Generated: ${new Date().toLocaleDateString()}

🛡️ Key Rights:
• Right to remain silent
• Right to refuse searches
• Right to ask "Am I free to leave?"
• Right to an attorney

💬 What to Say:
• "I am exercising my right to remain silent"
• "I do not consent to searches"
• "Am I free to leave?"
• "I want to speak to a lawyer"

⚠️ Important:
• Stay calm and respectful
• Keep hands visible
• Don't argue or resist
• Remember details for later

Generated by Zara Rights - Your instant legal guide
      `,
      shareUrl: `${window.location.origin}/shared/${Date.now()}`,
      qrCode: null
    }
  }

  const handleShare = async () => {
    if (navigator.share && generatedCard) {
      try {
        await navigator.share({
          title: generatedCard.title,
          text: generatedCard.content,
          url: generatedCard.shareUrl
        })
      } catch (error) {
        console.error('Share failed:', error)
        handleCopy()
      }
    } else {
      handleCopy()
    }
  }

  const handleCopy = async () => {
    if (generatedCard) {
      try {
        await navigator.clipboard.writeText(generatedCard.content)
        setCopied(true)
        setTimeout(() => setCopied(false), 2000)
      } catch (error) {
        console.error('Copy failed:', error)
      }
    }
  }

  const handleDownload = () => {
    if (generatedCard) {
      const blob = new Blob([generatedCard.content], { type: 'text/plain' })
      const url = URL.createObjectURL(blob)
      const a = document.createElement('a')
      a.href = url
      a.download = `${generatedCard.title.replace(/[^a-zA-Z0-9]/g, '_')}.txt`
      document.body.appendChild(a)
      a.click()
      document.body.removeChild(a)
      URL.revokeObjectURL(url)
    }
  }

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-center space-x-4">
        <button
          onClick={onBack}
          className="p-2 text-white hover:bg-white/20 rounded-lg transition-colors"
        >
          <ArrowLeft className="w-5 h-5" />
        </button>
        <div>
          <h2 className="text-xl font-bold text-white">Shareable Rights Card</h2>
          <p className="text-white/80 text-sm">Generated summary for easy sharing</p>
        </div>
      </div>

      {/* Card Preview */}
      <div className="bg-white rounded-lg shadow-card overflow-hidden">
        {isGenerating ? (
          <div className="p-8 text-center">
            <div className="animate-spin w-8 h-8 border-4 border-primary border-t-transparent rounded-full mx-auto mb-4"></div>
            <p className="text-text-secondary">Generating your rights card...</p>
          </div>
        ) : generatedCard ? (
          <div className="p-6">
            <h3 className="text-lg font-bold text-text-primary mb-4">{generatedCard.title}</h3>
            <div className="bg-gray-50 rounded-lg p-4 mb-6">
              <pre className="text-sm text-text-primary whitespace-pre-wrap font-sans">
                {generatedCard.content}
              </pre>
            </div>
            
            {/* Session Info */}
            {session && (
              <div className="border-t pt-4 text-sm text-text-secondary">
                <p>Session ID: {session.sessionId}</p>
                <p>Duration: {Math.round((session.endTime - session.startTime) / 1000)}s</p>
                {session.location && <p>Location: Coordinates recorded</p>}
                {session.alertSent && <p>Emergency alert: Sent to contacts</p>}
              </div>
            )}
          </div>
        ) : null}
      </div>

      {/* Action Buttons */}
      {generatedCard && (
        <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
          <CallToActionButton
            variant="primary"
            icon={<Share2 className="w-5 h-5" />}
            title="Share"
            onClick={handleShare}
          />
          <CallToActionButton
            variant="secondary"
            icon={copied ? <Check className="w-5 h-5" /> : <Copy className="w-5 h-5" />}
            title={copied ? "Copied!" : "Copy Text"}
            onClick={handleCopy}
          />
          <CallToActionButton
            variant="secondary"
            icon={<Download className="w-5 h-5" />}
            title="Download"
            onClick={handleDownload}
          />
        </div>
      )}

      {/* Usage Tips */}
      <div className="bg-blue-50 border border-blue-200 rounded-lg p-4">
        <h4 className="font-semibold text-blue-900 mb-2">Sharing Tips</h4>
        <ul className="text-sm text-blue-800 space-y-1">
          <li>• Share with family members so they know your rights</li>
          <li>• Keep a copy saved on your device for quick access</li>
          <li>• Use this as a reference during interactions</li>
          <li>• Share on social media to educate others</li>
        </ul>
      </div>
    </div>
  )
}